### ISSUE TITLE
Loss of information

### ISSUE THREAD

**Issue by awadoumbia** [PDL-2019-2020-GR8/PDL_2018_2019_GR6#12]
I remark a different number of table extracted in the html extractor and the wiki extractor, which is surely due to the different criteria selection of tables.
The html extractor is able to extract arrays with colored columns, with links which is not the case with the extractor wiki.
I also note that with the two extractors a loss of information precisely on the title 14.

**Comment by mrothniel** [comment]
You say title 14 can you give the description of title 14?
We have not same part  URL directory
